local ShoppingCartUI = require("ShoppingCartUI")
local TestCreateFrontBox = require("TestCreateFrontBox")
local TestDestroyedUnitHandleProbe = require("TestDestroyedUnitHandleProbe")
local TestAttachmentHelper = require("TestAttachmentHelper")
local TestSceneUI = require("TestSceneUI")
local MainSessionEntry = require("MainSessionEntry")

LuaAPI.global_register_trigger_event({ EVENT.GAME_INIT }, function()
    MainSessionEntry.init()
    -- require("UICheck")
    -- ShoppingCartUI.init()
    TestCreateFrontBox.init()
    -- TestDestroyedUnitHandleProbe.init()
    TestAttachmentHelper.init()
    TestSceneUI.init()
    -- require("Test")
end)
